/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLDemoEventEmitterElement extends HTMLStencilElement {

  }
  var HTMLDemoEventEmitterElement: {
    prototype: HTMLDemoEventEmitterElement;
    new (): HTMLDemoEventEmitterElement;
  };
  interface HTMLElementTagNameMap {
    'demo-event-emitter': HTMLDemoEventEmitterElement;
  }
  interface ElementTagNameMap {
    'demo-event-emitter': HTMLDemoEventEmitterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'demo-event-emitter': JSXElements.DemoEventEmitterAttributes;
    }
  }
  namespace JSXElements {
    export interface DemoEventEmitterAttributes extends HTMLAttributes {
      'onDemoEvent'?: (event: CustomEvent) => void;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
